# Use an official Node runtime as the base image
FROM node:20-slim
# Copy the application files into the container
COPY app.js ./
# Specify terminal command for running the application
CMD ["node", "app.js"]